apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: 5min-policy
  namespace: kube-system
policy:
  interval:
    intervalMinutes: 5
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: petmigrationschedule
  namespace: kube-system
spec:
  template:
    spec:
      clusterPair: gcp
      includeResources: true
      startApplications: false
      namespaces:
      - petclinic
  schedulePolicyName: 5min-policy
